config/routes.rb
Rails.application.routes.draw do

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用(admin)
namespace :admin do
  get root to: 'homes#top'

  resources :items, except:[:destroy]

  resources :genres, except:[:new, :show, :destroy]

  resources :customers, except:[:new, :create, :destroy]

  resources :orders, only:[:show, :update]
  get '/admin/orders/:id' => 'orders#show'

  resources :order_details, only:[:update]
end



# 顧客用(public)
scope module: :public do
  root to: 'homes#top'
  get "/homes/about" => "homes#about"

  resources :items, except: [:destroy]

  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
  get "customers/my_page" => "customers#show"
  get '/customers/information/edit' => 'customers#edit'
  put 'customer/update' => 'customers#update'
  patch '/customers/information' => 'customers#update'
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, except:[:show, :new, :edit]

  get '/orders/complete' => 'orders#complete'
  resources :orders, except:[:edit, :update, :destroy]
  post '/orders/confirm' => 'orders#confirm'

  resources :addresses, except:[:show]
end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postcode, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_display
  '〒' + postcode + ' ' + address# + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount,      presence: true
  validates :customer_id, presence: true
  validates :item_id,     presence: true

  def subtotal
    item.with_tax_price * amount
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postcode, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true

  def address_display
  '〒' + postcode + ' ' + address# + ' ' + name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  belongs_to :genre
  has_one_attached :image

  def get_item_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  validates :name, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { "入金待ち": 0, "入金確認": 1, "制作中": 2, "発送準備中": 3, "発送済み": 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

   validates :order_id,           presence: true
   validates :item_id,            presence: true
   validates :amount,             presence: true

   enum making_status: { "製作不可": 0, "製作待ち": 1, "制作中": 2, "製作完了": 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    @genre.save
    redirect_to admin_genres_path
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end

  #ストロングパラメータ
  private
  def genre_params
    params.require(:genre).permit(:name, :is_enabled)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.all
    @orders = Order.page(params[:page]).reverse_order
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      flash[:item_created_error] = "商品情報が正常に保存されませんでした。"
      redirect_to new_admin_items_path
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      flash[:item_updated_error] = "商品情報が正常に保存されませんでした。"
      redirect_to edit_admin_item_path(@item)
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :image, :price, :genre_id, :is_active)
  end

end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController

  def index
    @orders = Order.all
  end

  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @total = 0
  end

  def update
    @order = Order.find(params[:id])
    @order.update(order_params)

    # [:order][:status]→orderの中のstatus
    if params[:order][:status] == "入金確認"
      # making_statusを製作待ちに更新
      @order.order_details.update(making_status: 1)
    end

    redirect_to request.referer

  end

  private

  def order_params
    params.require(:order).permit(:status, :making_status)
  end

end

app/controllers/admin/unlocks_controller.rb
# frozen_string_literal: true

class Admin::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/genres/edit.html.erb
<div class="container my-5 ">

  <div class="row m-5">
    <h4 style="background-color:#dcdcdc;">ジャンル編集</h4>
  </div>

  <div class="row align-items-center mt-3">
    <%= form_with model:@genre, url: admin_genre_path, method: :patch do |f| %>
      <div class="form-group row">
        <%= f.label :ジャンル名 %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

        <%= f.submit "変更を保存", class: "btn btn-success mx-auto mt-3" %>
    <% end %>
  </div>

</div>

app/views/admin/genres/index.html.erb
<div class="container my-5 ">

  <div class="row m-5">
    <h4 style="background-color:#dcdcdc;">ジャンル一覧・追加</h4>
  </div>

 <div class="mt-5 light-text">
      <%= form_with model:@genre, url: admin_genres_path, local:true do |f| %>
        <label class="text mx-5">ジャンル名</label>
        <%= f.text_field :name %>
        <%= f.submit '新規登録', class: "btn btn-success btn-sm mx-5" %>
      <% end %>
    </div>
 </div>

 <div class="row m-5">
    <table class="table col-md-4 border">
      <thead class="table-active text">
        <th>ジャンル</th>
        <th></th>
      </thead>
       <tbody>
          <% @genres.each do |genre| %>
            <tr>
              <td><%= genre.name %></td>
              <td><%= link_to "編集する", edit_admin_genre_path(genre), class: "btn btn-success btn-sm" %></td>
            </tr>
          <% end %>
        </tbody>
    </table>
 </div>


</div>

app/views/admin/homes/top.html.erb
<div class="container my-5 ">

  <div class="row m-5">
    <h4>注文履歴一覧</h4>
  </div>

  <div class="row mt-5">
    <table class="table table-hover">

      <thead>
        <tr class="table-active text">
          <th>購入日時</th>
          <th>購入者</th>
          <th>注文個数</th>
          <th>注文ステータス</th>
        </tr>
      </thead>

      <tbody>
        <% @orders.each do |order| %>
        <tr>
          <th><%= link_to admin_order_path(order), class:"text-dark"  do %>
          <%= order.created_at.strftime('%Y/%m/%d %H:%M:%S') %>
          <% end %>
          </th>
          <th><%= order.name %></th>
          <th><%= order.order_details.count %></th>
          <th><%= order.status %></th>
    	 </tr>
    	 <% end %>
      </tbody>

    </table>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container my-5">
  <div class="row mb-5">
    <h2 style="background-color:#dcdcdc;">商品編集</h2>
  </div>

    <!--colのサイズ設定-->
    <%= form_with model: @item, url: admin_item_path(@item.id), local: true do |f| %>
      <table>
        <tr>
          <th>商品画像</th>
          <td><%= f.file_field :image %></td>
        </tr>
        <tr><td>&nbsp;</td></tr>
        <tr>
          <th>商品名</th>
          <td><%= f.text_field :name %></td>
        </tr>
        <tr><td>&nbsp;</td></tr>
        <tr>
          <th>商品説明</th>
          <td><%= f.text_area :explanation %></td>
        </tr>
        <tr><td>&nbsp;</td></tr>
        <tr>
          <th>ジャンル</th>
          <td><%= f.collection_select(:genre_id, @genres, :id, :name, prompt: "選択してください") %></td>
        </tr>
        <tr><td>&nbsp;</td></tr>
        <tr>
          <th>税抜価格</th>
          <td><%= f.text_field :price %>円</td>
        </tr>
        <tr><td>&nbsp;</td></tr>
        <tr>
          <th>販売ステータス</th>
          <td>
            <%= f.radio_button :is_active, :true %>
            <%= f.label :is_active, "販売中" %>
            <%= f.radio_button :is_active, :false %>
            <%= f.label :is_active, "販売停止中" %>
          </td>
        </tr>
      </table>
      <br>
      <%= f.submit "変更を保存", class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/admin/items/index.html.erb
<div class="container my-5">
  <div class="row">
    <h2 style="background-color:#dcdcdc;">商品一覧</h2>
  </div>

    <div class="col-md-1 offset-md-9">
      <%= link_to new_admin_item_path do %>
        <i class="fas fa-plus-circle fa-3x"></i>
      <% end %>
    </div>
  </div>

    <div class="row　ml-5">
      <table class="table cart_products">
        <tr>
          <th class="col-md-1">商品ID</th>
          <th class="col-md-3">商品名</th>
          <th class="col-md-2">税抜価格</th>
          <th class="col-md-2">ジャンル</th>
          <th class="col-md-2">ステータス</th>
        </tr>
        <% @items.each do |item| %>
        <tr>
          <td class="col-md-1"><%= item.id %></td>
          <td class="col-md-3"><%= link_to item.name, admin_item_path(item.id) %></td>
          <td class="col-md-2"><%= item.price %></td>
          <td class="col-md-2"><%= item.genre.name %></td>
          <td class="col-md-2"><%= item.is_active ? "販売中" : "販売停止中" %></td>
        </tr>
        <% end %>
      </table>
    </div>
</div>

app/views/admin/items/new.html.erb
<div class="container my-5">

  <div class="row m-5">
    <h4 style="background-color:#dcdcdc;">商品新規登録</h4>
  </div>

  <%= form_with model: @item, url: admin_items_path,local: true do |f| %>

      <div class="col-sm-5">
        <%= f.label :商品画像 %>
        <%= f.file_field :image %>
      </div>

      <div class="col-sm-5 mt-3">
        <div class="form-group row">
          <%= f.label :商品名, class: "col-sm-4" %>
          <%= f.text_field :name, class: "form-control col-sm-8" %>
        </div>

        <div class="form-group row">
          <%= f.label :商品説明, class: "col-sm-4" %>
          <%= f.text_area :description, class: "form-control col-sm-8" %>
        </div>

        <div class="form-group row">
          <%= f.label :ジャンル, class: "col-sm-4" %>
          <%= f.collection_select :genre_id, Genre.all, :id, :name, class: "form-control col-sm-8" %>
        </div>

        <div class="form-group row">
          <%= f.label :税抜価格, class: "col-sm-4" %>
          <%= f.text_field :price, class: "form-control col-sm-7" %>
          <span class="mt-auto ml-3">円</span>
        </div>

        <div class="form-group row">
          <%= f.label :販売ステータス, class: "col-sm-4" %>
          <%= f.select :sale_status, [["販売中", "販売中"], ["販売停止中","販売停止中"]], class: "form-control col-sm-8" %>
        </div>
      </div>

      <div class="col-sm-2 mt-auto ml-5">
        <%= f.submit :新規登録, class: "btn btn-success" %>
      </div>

    </div>

  <% end %>

</div>

app/views/admin/items/show.html.erb
<div class="container my-5">
  <div class="row">
    <h2 style="background-color:#dcdcdc;">商品詳細</h2>
  </div>

  <div class="row mt-3">
    <div class="offset-sm-1 col-sm-3">
      <%= image_tag @item.get_item_image(100,100) %>
    </div>

    <div class="col-sm-4">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <td>商品名</td>
            <td><%= @item.name %></td>
          </tr>

          <tr>
            <td>商品説明</td>
            <td><%= @item.description %></td>
          </tr>

          <tr>
            <td>ジャンル</td>
            <td><%= @item.genre.name %></td>
          </tr>

          <tr>
            <td>税込価格(税抜価格)</td>
            <td>
              <%= @item.price %>(<%= (@item.price * 1.1).floor %>)円
            </td>
          </tr>

          <tr>
            <td>販売ステータス</td>
            <td>
              <% if @item.is_active %>
               販売中
              <% else %>
               販売停止中
              <% end %>
            </td>
          </tr>
        </tbody>

      </table>
    </div>
  </div>

  <div class="row">
    <div class="offset-sm-5 col-sm-2 mt-3">
      <%= link_to "編集する", edit_admin_item_path(@item), class: "btn btn-success" %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container my-5 ">

  <div class="row m-5">
    <h4 style="background-color:#dcdcdc;">注文履歴詳細</h4>
  </div>

  <div class="col-6">
    <table class="order-customer">
      <tr>
        <th>購入者</th>
        <td><%= @order.name %></td>
      </tr>
      <tr>
        <th>注文日</th>
        <td><%= @order.created_at.strftime('%Y/%m/%d') %></td>
      </tr>
      <tr>
        <th>配送先</th>
        <td><%= @order.address %></td>
      </tr>
      <tr>
        <th>支払方法</th>
        <td><%= Order.payment_methods_i18n[@order.payment_method] %></td>
      </tr>
      <tr>

        <th>注文ステータス</th>
        <td>
          <!--enum-->
          <%= form_with(model: @order, url: admin_order_path, local: true) do |f| %>
          <%= f.select :status, Order.statuses_i18n.invert %>
          <%= f.submit "更新", class:"btn btn-success" %>
           <% end %>
        </td>

      </tr>
    </table>
  </div>
  <div class="row mt-3">
    <div class="col-7">
      <table class="table table-bordered">
        <thead>
          <th>商品名</th>
          <th>単価（税込）</th>
          <th>数量</th>
          <th>小計</th>
          <th>製作ステータス</th>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
          <tr>
            <td><%= order_detail.item.name %></td>
            <td><%= (order_detail.price).to_s(:delimited) %>  円</td>
            <td><%= (order_detail.amount).to_s(:delimited)%>  個</td>
            <td><%= (order_detail.price * order_detail.amount).to_s(:delimited) %>  円</td>
            <% @total +=  order_detail.price * order_detail.amount %>
            <td>
              <div>

                <%= form_with(model:[@order, order_detail], url: admin_order_detail_path(@order,order_detail), local: true) do |f| %>
                  <%= f.select :making_status,OrderDetail.making_statuses_i18n.invert %>
                  <%= f.submit "更新", class:"btn btn-success" %>
                <% end %>
              </div>
           </td>
         </tr>
         <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-4">
       <table>
        <tr>
          <th>商品合計</th>
          <td><%= (@total).to_s(:delimited) %>円</td>
        </tr>
        <tr>
          <th>送料</th>
          <td>800円</td>
        </tr>
        <tr>
          <th>請求金額合計</th>
          <td><%= (@total + 800).to_s(:delimited) %>円</td>
        </tr>
      </table>
    </div>
  </div>
</div>