config/routes.rb
Rails.application.routes.draw do

# URL /admin/sign_in ...
devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}

# URL /customers/sign_in ...
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

# 管理者用(admin)
namespace :admin do
  get root to: 'homes#top'

  resources :items, except:[:destroy]

  resources :genres, except:[:new, :show, :destroy]

  resources :customers, except:[:new, :create, :destroy]

  resources :orders, only:[:show, :update]
  get '/admin/orders/:id' => 'orders#show'

  resources :order_details, only:[:update]
end



# 顧客用(public)
scope module: :public do
  root to: 'homes#top'
  get "/homes/about" => "homes#about"

  resources :items, except: [:destroy]

  get 'customers/unsubscribe' => 'customers#unsubscribe', as: 'unsubscribe'
  patch 'customers/withdraw' => 'customers#withdraw', as: 'withdraw'
  get "customers/my_page" => "customers#show"
  get '/customers/information/edit' => 'customers#edit'
  put 'customer/update' => 'customers#update'
  patch '/customers/information' => 'customers#update'
  delete '/cart_items/destroy_all' => 'cart_items#destroy_all'
  resources :cart_items, except:[:show, :new, :edit]

  get '/orders/complete' => 'orders#complete'
  resources :orders, except:[:edit, :update, :destroy]
  post '/orders/confirm' => 'orders#confirm'

  resources :addresses, except:[:show]
end


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  validates :postcode, presence: true
  validates :address, presence: true
  validates :name, presence: true

  def address_display
  '〒' + postcode + ' ' + address# + ' ' + name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :image
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :customer
  belongs_to :item

  validates :amount,      presence: true
  validates :customer_id, presence: true
  validates :item_id,     presence: true

  def subtotal
    item.with_tax_price * amount
  end

  def with_tax_price
    (price * 1.1).floor
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :cart_items, dependent: :destroy
  has_many :addresses, dependent: :destroy
  has_many :orders, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name_kana, presence: true
  validates :last_name_kana, presence: true
  validates :postcode, presence: true
  validates :phone_number, presence: true
  validates :address, presence: true

  def address_display
  '〒' + postcode + ' ' + address# + ' ' + name
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :name, presence: true
end

app/models/home.rb
class Home < ApplicationRecord
  has_one_attached :image

  def get_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end
end

app/models/item.rb
class Item < ApplicationRecord

  has_many :order_details, dependent: :destroy
  has_many :cart_items, dependent: :destroy

  belongs_to :genre
  has_one_attached :image

  def get_item_image(width, height)
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    image.variant(resize_to_limit: [width, height]).processed
  end

  def with_tax_price
    (price * 1.1).floor
  end

  validates :name, presence: true
  validates :price, presence: true
end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :customer
  has_many :order_details, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }

  enum status: { "入金待ち": 0, "入金確認": 1, "制作中": 2, "発送準備中": 3, "発送済み": 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord

  belongs_to :order
  belongs_to :item

   validates :order_id,           presence: true
   validates :item_id,            presence: true
   validates :amount,             presence: true

   enum making_status: { "製作不可": 0, "製作待ち": 1, "制作中": 2, "製作完了": 3 }

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  
  def top
    @orders = Order.all
    @orders = Order.page(params[:page]).reverse_order
  end
  
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController

  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      flash[:item_created_error] = "商品情報が正常に保存されませんでした。"
      redirect_to new_admin_items_path
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @genres = Genre.all
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item)
    else
      flash[:item_updated_error] = "商品情報が正常に保存されませんでした。"
      redirect_to edit_admin_item_path(@item)
    end
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :image, :price, :genre_id, :is_active)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_header.html.erb
<!-- ヘッダー用部分テンプレート -->

<header class="shadow-sm">
  <nav class="navbar navbar-expand-lg navbar-light">
    <a class="navbar-brand " href="/"><%= image_tag 'naganocake.png', size: "100x100" %>
      <div class="collapse navbar-collapse justify-content-end">
         <ul class="navbar-nav">
           <% if customer_signed_in? %>
                <li class="mx-3"><%= link_to "マイページ", customers_my_page_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "カート", cart_items_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: "btn btn-outline-dark" %></li>
              <% elsif admin_signed_in? %>
                <li class="mx-3"><%= link_to "商品登録", new_admin_item_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "商品一覧", admin_items_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "会員一覧", admin_customers_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "注文履歴一覧", admin_root_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "ジャンル一覧", admin_genres_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "btn btn-outline-dark" %></li>
              <% else %>
                <li class="mx-3"><%= link_to "About", homes_about_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "商品一覧", items_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "新規登録", new_customer_registration_path, class: "btn btn-outline-dark" %></li>
                <li class="mx-3"><%= link_to "ログイン", new_customer_session_path, class: "btn btn-outline-dark" %></li>
              <% end %>
              <div>
                <form class="d-flex flex-column">
                  <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                </form>
              </div>
         </ul>
      </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/f1e9e2c6a2.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div id=”wrapper”>
      <% if admin_signed_in? %>
        <%= render 'layouts/header' %>
      <% else %>
        <%= render 'layouts/header' %>
      <% end %>
      <main>
        <%= yield %>
      </main>
    </div>
  </body>
</html>